# install additional R packages
install.packages('pak', repos = 'https://r-lib.github.io/p/pak/stable/')
pak::pak('here')
pak::pak('gtsummary@2.3.0')
pak::pak('tidymodels@1.3.0')
pak::pak('markdown@2.0')
pak::pak('rmarkdown@2.29')
pak::pak('card@0.2.5')
pak::pak('cardx@0.2.5')
pak::pak('ggsurvfit@1.1.0')
pak::pak('survival@3.8-3')
pak::pak('gt@1.0.0')
pak::pak('broom@1.0.9')
pak::pak('smd@0.8.0')
pak::pak('quarto@1.5.0')
pak::pak('yaml@2.3.10')
pak::pak('languageserver@0.3.16')
pak::pak('WeightIt@1.4.0')
pak::pak('MatchIt@4.7.2')
pak::pak('MatchThem@1.2.1')
pak::pak('cobalt@4.6.0')
pak::pak('smdi@0.3.1')
pak::pak('janickweberpals/encore.analytics')